### ISSUE TITLE
Put examples and plots in docs

### ISSUE THREAD

**Issue by CJ-Wright** [networkx/grave#28]
Is there any interest in putting the examples (and their output plots) into the docs?

**Comment by NelleV** [comment]
Hi @CJ-Wright 
I'm not sure what you mean by this. Could you extend a bit?
We already have a gallery, and the plots are linked into the API documentation (see http://grave.readthedocs.io/en/latest/generated/api/grave.grave.plot_network.html#grave.grave.plot_network). Considering you've contributed to one of the examples already, I'm sure you have something else in mind :smile:.

**Comment by CJ-Wright** [comment]
Sorry I was looking at the docs listed on the github page. Are those the correct docs or are the rtd the correct docs?

**Comment by NelleV** [comment]
I believe it is the same (the gallery is here: https://networkx.github.io/grave/latest/gallery/index.html)

**Comment by CJ-Wright** [comment]
Ah ok, I was clicking on the wrong link. It seems that the `stable` docs are broken. https://networkx.github.io/grave/stable/

**Comment by tacaswell** [comment]
Because we do not have a tag, there is no stable ;)

**Comment by CJ-Wright** [comment]
Fair, although I would remove that link since it is a bit of deceptive advertising :smile:
