### ISSUE TITLE
Can't pickle local object subgraph_view.<locals>.reverse_edge

### ISSUE THREAD

**Issue by monowaranjum** [networkx/grave#41]
Hi, I was trying to use pickle to dump a relatively large ```MultiDiGraph``` into a pickle file. But it is not working. I don't know why. I tried this method on smaller digraphs before and it usually owrks.

![image](https://user-images.githubusercontent.com/19803082/234102429-94529cf4-9bde-4147-8169-10e1154fb436.png)

**Comment by dschult** [comment]
You should probably make a full graph rather than a subgraph view. The
subgraph view is just a view to the real graph and pickle doesn't have
access to the original graph. But if you use:  newgraph = graph.copy() and
then pickle the newgraph the pickle should work.

**Comment by xiaofeifei-1** [comment]
H = loaded_graph.subgraph(selected_nodes)
newgraph = H.copy()

file_path = "./filtered_graph.pkl"
with open(file_path, 'wb') as file:
    pickle.dump(newgraph, file)
 
it works，thanks
