### ISSUE TITLE
README.md example should be runnable.

### ISSUE THREAD

**Issue by ivanov** [networkx/grave#6]
@camillescott  17a9a43a41607bedbd8149ab26a48f171ed1b163 reverted a fix I committed to the README.md. I'll push out another fix.

**Comment by ivanov** [comment]
ca94702602e4b2c18d43ed2cf90439ce33c0f92e re-introduces the error.

**Comment by camillescott** [comment]
Sorry, seems we're editing via the github interface at the same time.

**Comment by ivanov** [comment]
I'm using CLI, I think GH unhelpful doesn't tell you when you commit through the web API if there's been a change that went into master in the meantime, and just assumes you wanted to clobber over it. I re-cherry-picked the fixing commit, so we should be good to go now. My best to everyone at the workshop if you're all still hacking away over there. Nice meeting you 🍻
